"""empty message

Revision ID: f27e5c4c1b2b
Revises: 9bec83e76564
Create Date: 2020-06-02 11:10:24.173004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27e5c4c1b2b'
down_revision = '9bec83e76564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'about_me', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'about_me', type_='unique')
    # ### end Alembic commands ###
