"""empty message

Revision ID: 563155482c82
Revises: 6d4ecda67872
Create Date: 2020-05-26 16:59:38.189810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563155482c82'
down_revision = '6d4ecda67872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'article', 'type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'type_id')
    op.drop_table('type')
    # ### end Alembic commands ###
