"""empty message

Revision ID: 58c08900f494
Revises: 5acbcdb5d19f
Create Date: 2020-06-09 14:57:32.508184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c08900f494'
down_revision = '5acbcdb5d19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('isdelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isdelete')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
