"""empty message

Revision ID: 00143c0d9846
Revises: 
Create Date: 2020-06-08 16:32:49.368235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00143c0d9846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.Column('udatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
