"""empty message

Revision ID: 24901c12048f
Revises: cc0dca61130f
Create Date: 2020-05-22 16:24:46.678661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24901c12048f'
down_revision = 'cc0dca61130f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
